# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
null = np.zeros(10)

null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 2. Create a vector with values ranging from 10 to 49.

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Create a 3x3 matrix with values ranging from 0 to 8


In [4]:
matrix = np.arange(0,9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [5]:
array = np.array([1,2,0,0,4,0])
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

### 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [8]:
array_10 = np.random.random((10,10))
print(array_10)
print(np.min(array_10))
print(np.max(array_10))

[[0.11398972 0.70369624 0.45707346 0.85172731 0.67108239 0.31981008
  0.35663622 0.94178339 0.84422538 0.38338734]
 [0.58848156 0.79948396 0.78356569 0.09294451 0.8232534  0.17479251
  0.14084744 0.8610505  0.46432406 0.28235898]
 [0.41143679 0.8564944  0.2414781  0.01156627 0.90740387 0.30186776
  0.04643197 0.71925425 0.81125531 0.03311314]
 [0.07117481 0.90874987 0.46625602 0.07811615 0.57784808 0.34547656
  0.71321226 0.11205157 0.03936585 0.16749203]
 [0.06511199 0.05862191 0.72233065 0.2350048  0.62128605 0.12081844
  0.80921745 0.56692115 0.78575357 0.67062989]
 [0.58392863 0.98589746 0.89754389 0.96117527 0.24056652 0.70262613
  0.66943895 0.53809294 0.33846765 0.57852884]
 [0.07286603 0.38100238 0.36188722 0.41349329 0.63498434 0.16506982
  0.06385922 0.49908668 0.16109949 0.6098221 ]
 [0.70785765 0.97983408 0.18170033 0.10848492 0.46597065 0.51351263
  0.33535483 0.28801233 0.18728508 0.07515769]
 [0.34528003 0.12934559 0.32323386 0.32665618 0.32984053 0.66134863
  0.96588172

### 6. Create a random vector of size 30 and find the mean value.


In [10]:
vector = np.random.random((5,6))
np.mean(vector)                          

0.6166439121373806